In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Concrete%20Compressive%20Strength.csv')

In [ ]:
df.head()

Cement (kg in a m^3 mixture)  Blast Furnace Slag (kg in a m^3 mixture)  \
0                         540.0                                       0.0   
1                         540.0                                       0.0   
2                         332.5                                     142.5   
3                         332.5                                     142.5   
4                         198.6                                     132.4   

   Fly Ash (kg in a m^3 mixture)  Water (kg in a m^3 mixture)  \
0                            0.0                        162.0   
1                            0.0                        162.0   
2                            0.0                        228.0   
3                            0.0                        228.0   
4                            0.0                        192.0   

   Superplasticizer (kg in a m^3 mixture)  \
0                                     2.5   
1                                     2.5   
2                                     0.0   
3                                     0.0   
4                                     0.0   

   Coarse Aggregate (kg in a m^3 mixture)  \
0                                  1040.0   
1                                  1055.0   
2                                   932.0   
3                                   932.0   
4                                   978.4   

   Fine Aggregate (kg in a m^3 mixture)  Age (day)  \
0                                 676.0         28   
1                                 676.0         28   
2                                 594.0        270   
3                                 594.0        365   
4                                 825.5        360   

   Concrete Compressive Strength(MPa, megapascals)   
0                                         79.986111  
1                                         61.887366  
2                                         40.269535  
3                                         41.052780  
4                                         44.296075

In [ ]:
df.shape

(1030, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                                            Non-Null Count  Dtype  
---  ------                                            --------------  -----  
 0   Cement (kg in a m^3 mixture)                      1030 non-null   float64
 1   Blast Furnace Slag (kg in a m^3 mixture)          1030 non-null   float64
 2   Fly Ash (kg in a m^3 mixture)                     1030 non-null   float64
 3   Water (kg in a m^3 mixture)                       1030 non-null   float64
 4   Superplasticizer (kg in a m^3 mixture)            1030 non-null   float64
 5   Coarse Aggregate (kg in a m^3 mixture)            1030 non-null   float64
 6   Fine Aggregate (kg in a m^3 mixture)              1030 non-null   float64
 7   Age (day)                                         1030 non-null   int64  
 8   Concrete Compressive Strength(MPa, megapascals)   1030 non-null   float64
dtypes: float64(8), int64

In [ ]:
df.describe()

Cement (kg in a m^3 mixture)  Blast Furnace Slag (kg in a m^3 mixture)  \
count                   1030.000000                               1030.000000   
mean                     281.165631                                 73.895485   
std                      104.507142                                 86.279104   
min                      102.000000                                  0.000000   
25%                      192.375000                                  0.000000   
50%                      272.900000                                 22.000000   
75%                      350.000000                                142.950000   
max                      540.000000                                359.400000   

       Fly Ash (kg in a m^3 mixture)  Water (kg in a m^3 mixture)  \
count                    1030.000000                  1030.000000   
mean                       54.187136                   181.566359   
std                        63.996469                    21.355567   
min                         0.000000                   121.750000   
25%                         0.000000                   164.900000   
50%                         0.000000                   185.000000   
75%                       118.270000                   192.000000   
max                       200.100000                   247.000000   

       Superplasticizer (kg in a m^3 mixture)  \
count                             1030.000000   
mean                                 6.203112   
std                                  5.973492   
min                                  0.000000   
25%                                  0.000000   
50%                                  6.350000   
75%                                 10.160000   
max                                 32.200000   

       Coarse Aggregate (kg in a m^3 mixture)  \
count                             1030.000000   
mean                               972.918592   
std                                 77.753818   
min                                801.000000   
25%                                932.000000   
50%                                968.000000   
75%                               1029.400000   
max                               1145.000000   

       Fine Aggregate (kg in a m^3 mixture)    Age (day)  \
count                           1030.000000  1030.000000   
mean                             773.578883    45.662136   
std                               80.175427    63.169912   
min                              594.000000     1.000000   
25%                              730.950000     7.000000   
50%                              779.510000    28.000000   
75%                              824.000000    56.000000   
max                              992.600000   365.000000   

       Concrete Compressive Strength(MPa, megapascals)   
count                                       1030.000000  
mean                                          35.817836  
std                                           16.705679  
min                                            2.331808  
25%                                           23.707115  
50%                                           34.442774  
75%                                           46.136287  
max                                           82.599225

In [ ]:
df = df.rename(columns={'Cement (kg in a m^3 mixture)':"cement",'Blast Furnace Slag (kg in a m^3 mixture)':"Slag",'Fly Ash (kg in a m^3 mixture)':"Fly Ash",'Water (kg in a m^3 mixture)':"Water",
                        'Superplasticizer (kg in a m^3 mixture)':"Superplasticizer",'Coarse Aggregate (kg in a m^3 mixture)':"Coarse Aggregate",'Fine Aggregate (kg in a m^3 mixture)':
                        "Fine Aggregate",'Age (day)':"age",'Concrete Compressive Strength(MPa, megapascals)':"Strength"})

In [ ]:
df.head()

cement   Slag  Fly Ash  Water  Superplasticizer  Coarse Aggregate  \
0   540.0    0.0      0.0  162.0               2.5            1040.0   
1   540.0    0.0      0.0  162.0               2.5            1055.0   
2   332.5  142.5      0.0  228.0               0.0             932.0   
3   332.5  142.5      0.0  228.0               0.0             932.0   
4   198.6  132.4      0.0  192.0               0.0             978.4   

   Fine Aggregate  age  Concrete Compressive Strength(MPa, megapascals)   
0           676.0   28                                         79.986111  
1           676.0   28                                         61.887366  
2           594.0  270                                         40.269535  
3           594.0  365                                         41.052780  
4           825.5  360                                         44.296075

In [ ]:
df.columns

Index(['cement', 'Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'age',
       'Concrete Compressive Strength(MPa, megapascals) '],
      dtype='object')

In [ ]:
df['age'].value_counts

<bound method IndexOpsMixin.value_counts of 0        28
1        28
2       270
3       365
4       360
       ... 
1025     28
1026     28
1027     28
1028     28
1029     28
Name: age, Length: 1030, dtype: int64>

In [ ]:
df.groupby('age').mean()

cement        Slag     Fly Ash       Water  Superplasticizer  \
age                                                                     
1    442.500000    0.000000    0.000000  193.000000          0.000000   
3    286.577910   65.977090   57.162313  176.187388          6.614754   
7    312.923810   92.943651   12.642857  183.287302          3.751667   
14   246.174839   18.589194   97.850806  173.387258          6.672048   
28   265.443388   86.285012   62.794706  183.059082          6.994605   
56   294.168571   55.221209   85.041209  167.446264          9.853593   
90   284.140741   88.524074    0.000000  200.768519          0.000000   
91   392.263636  148.809091    0.000000  157.763636         15.154545   
100  220.900769   22.164038  116.668269  169.442500          7.955135   
120  330.000000    0.000000    0.000000  192.000000          0.000000   
180  331.334615   49.319231    0.000000  207.038462          0.000000   
270  376.884615   72.346154    0.000000  218.615385          0.000000   
360  267.533333   56.966667    0.000000  191.833333          0.000000   
365  319.321429   67.178571    0.000000  218.642857          0.000000   

     Coarse Aggregate  Fine Aggregate  \
age                                     
1         1045.500000      688.000000   
3          977.247239      796.109478   
7          983.814286      768.103175   
14        1023.908548      800.114032   
28         956.059129      764.376635   
56         979.634396      798.487582   
90         966.137037      758.662963   
91         918.940909      802.336364   
100       1025.294808      809.443654   
120       1031.000000      820.000000   
180        979.900000      725.438462   
270        976.538462      627.615385   
360        998.066667      828.233333   
365        942.285714      690.071429   

     Concrete Compressive Strength(MPa, megapascals)   
age                                                    
1                                            9.452716  
3                                           18.981082  
7                                           26.050623  
14                                          28.751038  
28                                          36.748480  
56                                          51.890061  
90                                          40.480809  
91                                          69.806938  
100                                         47.668780  
120                                         39.647168  
180                                         41.730376  
270                                         51.272511  
360                                         40.696895  
365                                         43.557843

In [ ]:
y = df['age']

In [ ]:
y.shape

(1030,)

In [ ]:
y

0        28
1        28
2       270
3       365
4       360
       ... 
1025     28
1026     28
1027     28
1028     28
1029     28
Name: age, Length: 1030, dtype: int64

In [ ]:
X = df[['cement', 'Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'age',
       'Concrete Compressive Strength(MPa, megapascals) ']]

In [ ]:
X = df.drop('age',axis=1)

In [ ]:
X.shape

(1030, 8)

In [ ]:
X

cement   Slag  Fly Ash  Water  Superplasticizer  Coarse Aggregate  \
0      540.0    0.0      0.0  162.0               2.5            1040.0   
1      540.0    0.0      0.0  162.0               2.5            1055.0   
2      332.5  142.5      0.0  228.0               0.0             932.0   
3      332.5  142.5      0.0  228.0               0.0             932.0   
4      198.6  132.4      0.0  192.0               0.0             978.4   
...      ...    ...      ...    ...               ...               ...   
1025   276.4  116.0     90.3  179.6               8.9             870.1   
1026   322.2    0.0    115.6  196.0              10.4             817.9   
1027   148.5  139.4    108.6  192.7               6.1             892.4   
1028   159.1  186.7      0.0  175.6              11.3             989.6   
1029   260.9  100.5     78.3  200.6               8.6             864.5   

      Fine Aggregate  Concrete Compressive Strength(MPa, megapascals)   
0              676.0                                         79.986111  
1              676.0                                         61.887366  
2              594.0                                         40.269535  
3              594.0                                         41.052780  
4              825.5                                         44.296075  
...              ...                                               ...  
1025           768.3                                         44.284354  
1026           813.4                                         31.178794  
1027           780.0                                         23.696601  
1028           788.9                                         32.768036  
1029           761.5                                         32.401235  

[1030 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mm = MinMaxScaler()

In [ ]:
X = mm.fit_transform(X)

In [ ]:
X

array([[1.        , 0.        , 0.        , ..., 0.69476744, 0.20572002,
        0.9674449 ],
       [1.        , 0.        , 0.        , ..., 0.73837209, 0.20572002,
        0.7419643 ],
       [0.52625571, 0.39649416, 0.        , ..., 0.38081395, 0.        ,
        0.47264169],
       ...,
       [0.10616438, 0.38786867, 0.54272864, ..., 0.26569767, 0.46663322,
        0.26617018],
       [0.1303653 , 0.51947691, 0.        , ..., 0.54825581, 0.48896136,
        0.37918535],
       [0.36278539, 0.27963272, 0.39130435, ..., 0.18459302, 0.42022077,
        0.37461561]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.3, stratify = y, random_state= 2529)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((721, 8), (309, 8), (721,), (309,))

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
y_pred.shape

(309,)

In [ ]:
y_pred

array([ 28,  28, 100,  28,   3,   3,  28,   7,   3,   3,   7,  28,  28,
        28,  28,  28,   7,  28,  28,  28, 100,  28,  28,  28,  28,  28,
        28,  28,  28,  28,   7,  56,   3,  28,  28,   7,  28,  28,  28,
        28,  28,  28,  28,  28,  28,  28,  28,  28,  28,   7,  28,  28,
        28,  28,  28,   3,  28,  28,   3,   7,   7,  28,   3,  28,  28,
        28,   7,  28,   3,  28,  28,  28,  28,  28,  28,  28,  56,   7,
        28,  28,  28,  28,  28,  28,  28,  28,   3,  28,  28,  28,   3,
        28,  28,  28,  56,  28,   7,  28,  28,   3,   3,   7,  28,  28,
        28,  28,  28,  28,   3,  28,  28,   7,  28,  28,  28,  28,  28,
        28,  28,   3,  28,  28,  28,  28,  28,  28,  28,  28,  28,  28,
        28,   3,  28,  28,  28,  28,  28,  56,  28,  28,  28,  28,  28,
        28,  28,  28,  28,   7,  28,  28,  28,  28,  28,  28,  28,  28,
        28,  28,  28,  28,  28,  28,   7,  28,  28,  28,  28,  28,  28,
        28,  28,  28,   7,  28,  28,  28,  28,  28,  28,  28,   

In [ ]:
lr.predict_proba(X_test)

array([[0.00054516, 0.07062204, 0.02641774, ..., 0.00352827, 0.00149433,
        0.00436175],
       [0.00110651, 0.0613633 , 0.02636723, ..., 0.002238  , 0.00485924,
        0.00404297],
       [0.00088654, 0.03739786, 0.01292323, ..., 0.00186267, 0.00398222,
        0.00333043],
       ...,
       [0.00150443, 0.38412257, 0.36612258, ..., 0.00672076, 0.00608539,
        0.00869544],
       [0.00076951, 0.04209881, 0.01865457, ..., 0.00210193, 0.00298403,
        0.0023921 ],
       [0.00229013, 0.19305915, 0.25836396, ..., 0.01078298, 0.01081212,
        0.01531677]])

In [ ]:
!pip install scipy
!pip install sklearn.metrics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement sklearn.metrics (from versions: none)
ERROR: No matching distribution found for sklearn.metrics


In [ ]:
from sklearn.ensemble import AdaBoostRegressor

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[  0   0   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0  21   5   0  14   0   0   0   0   0   0   0   0   0]
 [  0   5  17   0  16   0   0   0   0   0   0   0   0   0]
 [  0   2   1   0  16   0   0   0   0   0   0   0   0   0]
 [  0   1   7   0 115   4   0   0   0   0   0   0   0   0]
 [  0   0   0   0  26   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0  16   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   6   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  12   1   0   0   3   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   8   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   4   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   2   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   4   0   0   0   0   0   0   0   0   0]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           3       0.72      0.53      0.61        40
           7       0.55      0.45      0.49        38
          14       0.00      0.00      0.00        19
          28       0.48      0.91      0.63       127
          56       0.17      0.04      0.06        27
          90       0.00      0.00      0.00        16
          91       0.00      0.00      0.00         6
         100       1.00      0.19      0.32        16
         120       0.00      0.00      0.00         1
         180       0.00      0.00      0.00         8
         270       0.00      0.00      0.00         4
         360       0.00      0.00      0.00         2
         365       0.00      0.00      0.00         4

    accuracy                           0.51       309
   macro avg       0.21      0.15      0.15       309
weighted avg       0.42      0.51      0.42       309



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
X_new = df.sample(1)

In [ ]:
X_new

cement   Slag  Fly Ash  Water  Superplasticizer  Coarse Aggregate  \
983   136.4  161.6    125.8  171.6              10.4             922.6   

     Fine Aggregate  age  Concrete Compressive Strength(MPa, megapascals)   
983           764.4   28                                         29.073134

In [ ]:
X_new.shape

(1, 9)

In [ ]:
X_new = X_new.drop('age', axis = 1)

In [ ]:
X_new

cement   Slag  Fly Ash  Water  Superplasticizer  Coarse Aggregate  \
983   136.4  161.6    125.8  171.6              10.4             922.6   

     Fine Aggregate  Concrete Compressive Strength(MPa, megapascals)   
983           764.4                                         29.073134

In [ ]:
X_new.shape

(1, 8)

In [ ]:
X_new = mm.fit_transform(X_new)

In [ ]:
y_pred_new = lr.predict(X_new)

In [ ]:
y_pred_new

array([28])

In [ ]:
lr.predict_proba(X_new)

array([[2.91032429e-04, 1.84431921e-01, 8.19328963e-02, 3.61337964e-03,
        7.15332910e-01, 1.01010208e-03, 6.01117295e-03, 4.49748625e-04,
        4.60735090e-04, 3.69031707e-04, 2.12111162e-03, 1.09947958e-03,
        7.10290366e-04, 2.16618868e-03]])